'use strict';
var fs = require('fs');
var parser = require('./LtJsGrammar.js'); //file generated by passing our syntax throught peg.js parser
var pathToLtJsContent = process.argv[2];
var escodegen = require("escodegen");

fs.readFile(pathToLtJsContent, 'utf8', function (err,data) {
  if (err) return console.log(err);
  var parsedSyntax = parser.parse(data);
  if(process.argv[3] !== 'execute' ){
	fs.writeFile('AST.js', JSON.stringify(parsedSyntax), function (err) {
	  if (err) return console.log(err);
	});
  }else{
	fs.writeFile('result.js', escodegen.generate(parsedSyntax), function (err) {
	  if (err) return console.log(err);
	});
	console.log(eval(escodegen.generate(parsedSyntax)));
  }
});