'use strict';
var PEG = require("pegjs");
var fs = require('fs');
var parser = require('./LtJsGrammar.js'); //file generated by passing our syntax thorught peg.js parse 
var pathToLtJsContent = process.argv[2];
var escodegen = require("escodegen");

fs.readFile(pathToLtJsContent, 'utf8', function (err,data) {
  if (err) return console.log(err);
  var parsedSyntax = parser.parse(data);
  if(process.argv[3] !== 'execute' ){
	console.log(JSON.stringify(parsedSyntax));
  }else{  
  //console.log('executing', escodegen.generate(parsedSyntax));
	console.log(eval(escodegen.generate(parsedSyntax)));
  }
});